# звук, который будет воспроизведен при замене предмета
replacing-sound: "BLOCK_GLASS_BREAK"

messages:
  reloaded: "Конфигурация перезагружена"
  no-permission: "У вас нет прав на использование этой команды"
  add-item: "Добавлен запрещенный предмет: {0}"